using System.Text.Json.Serialization;

namespace PnPPowerShell.MCPServer.Models;

// Short property names throughout: the index carries ~850 cmdlets and ~4400 parameters, so the keys
// would otherwise cost more than the values. Generated by build/Update-CommandIndex.ps1.
//
// Collections that are never optional use a nullable setter with a non-null getter, the same guard
// ScriptAnalysis uses: an explicit JSON null would otherwise replace the initializer and make every
// downstream LINQ call throw.

/// <summary>The search corpus: every cmdlet in the module this server was built against.</summary>
internal sealed class CommandIndexRoot
{
    private List<IndexedCommand> _commands = [];

    public string? Source { get; set; }

    /// <summary>The PnP.PowerShell version the index was generated from. Footered onto answers.</summary>
    public string? ModuleVersion { get; set; }

    public string DocsUrlTemplate { get; set; } = string.Empty;

    /// <summary>Superseded name to current name, e.g. Add-PnPAzureADGroupMember to Add-PnPEntraIDGroupMember.</summary>
    public Dictionary<string, string>? Aliases { get; set; }

    public List<IndexedCommand> Commands
    {
        get => _commands;
        set => _commands = value ?? [];
    }
}

/// <summary>One cmdlet, with everything search and parameter validation need.</summary>
internal sealed class IndexedCommand
{
    private List<IndexedParameter> _parameters = [];

    [JsonPropertyName("n")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("v")]
    public string Verb { get; set; } = string.Empty;

    [JsonPropertyName("u")]
    public string Noun { get; set; } = string.Empty;

    /// <summary>The synopsis with the permissions block removed; see <see cref="Permissions"/>.</summary>
    [JsonPropertyName("s")]
    public string Synopsis { get; set; } = string.Empty;

    /// <summary>Longer prose, capped at generation. Many synopses are too thin to match a real question.</summary>
    [JsonPropertyName("d")]
    public string? Description { get; set; }

    /// <summary>PnP prefixes its synopsis with a permissions list. Split out so it cannot skew scoring.</summary>
    [JsonPropertyName("perms")]
    public List<string>? Permissions { get; set; }

    [JsonPropertyName("p")]
    public List<IndexedParameter> Parameters
    {
        get => _parameters;
        set => _parameters = value ?? [];
    }

    /// <summary>Absent when the cmdlet has one unnamed set with nothing mandatory.</summary>
    [JsonPropertyName("ps")]
    public List<IndexedParameterSet>? ParameterSets { get; set; }

    [JsonPropertyName("e")]
    public List<string>? Examples { get; set; }

    /// <summary>Only present when the cmdlet's HelpUri is off the docs template.</summary>
    [JsonPropertyName("h")]
    public string? HelpUri { get; set; }
}

internal sealed class IndexedParameter
{
    [JsonPropertyName("n")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("t")]
    public string Type { get; set; } = string.Empty;
}

/// <summary>Members are indices into the command's parameter list rather than repeated names.</summary>
internal sealed class IndexedParameterSet
{
    private List<int> _members = [];
    private List<int> _required = [];

    [JsonPropertyName("n")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("d")]
    public bool IsDefault { get; set; }

    [JsonPropertyName("i")]
    public List<int> Members
    {
        get => _members;
        set => _members = value ?? [];
    }

    [JsonPropertyName("r")]
    public List<int> Required
    {
        get => _required;
        set => _required = value ?? [];
    }
}

// Source-generated: the server publishes native AOT, where reflection-based serialization is unavailable.
[JsonSerializable(typeof(CommandIndexRoot))]
[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal sealed partial class CommandIndexJsonContext : JsonSerializerContext;
